/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.castmart.jcountry;

public class JCountry {
    private static final CountryDB countryDB = new CountryDBImpl();
    
    public CountryDB getCountriesDB() {
        return countryDB;
    }
}
