/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6.1/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */
group = "com.jimdo"

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    id("pl.allegro.tech.build.axion-release") version "1.15.3"
}

// TO BE UPDATED ON EVERY RELEASE.
version = scmVersion.version

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.json:json:20230618")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.2")
}

tasks.withType<Test> {
    useJUnitPlatform()
    testLogging {
        events("PASSED", "FAILED", "SKIPPED")
        showStandardStreams = true
    }
}

//////////////////////////////////////////
// Publish and signature configuration. //
//////////////////////////////////////////

java {
    withJavadocJar()
    withSourcesJar()
}

afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("jcountry") {
                artifactId = "jcountry"
                from(components["java"])
                pom {
                    name.set("jcountry")
                    description.set("A java wrapper for the ISO country codes and translations inspired in pycountry")
                    url.set("https://github.com/Jimdo/jcountry")
                    licenses {
                        license {
                            name.set("GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1")
                            url.set("https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html")
                        }
                    }
                    developers {
                        developer {
                            id.set("castmart")
                            name.set("Juan Carlos Castaneda Martinez")
                            email.set("juan.castaneda@jimdo.com")
                        }
                    }
                    scm {
                        connection.set("scm:git:https://github.com/Jimdo/jcountry.git")
                        developerConnection.set("scm:git:https://github.com/Jimdo/jcountry.git")
                        url.set("https://github.com/Jimdo/jcountry")
                    }
                }
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/jimdo/packages")
                credentials {
                    username = "${System.getenv("MAVEN_USERNAME")}"
                    password = "${System.getenv("MAVEN_PASSWORD")}"
                }
            }
        }
    }
}
