/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.castmart.jcountry;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.*;

class JCountryTest {
    @Test
    void testJCountryReturnsCountryDB() {
        JCountry jcountry = new JCountry();
        CountryDB countryDB = jcountry.getCountriesDB();
        assertNotNull(countryDB, "getCountriesDB should return an instance of the countries DB");
    }

    @Test
    void testJCountryDBReadsJson() {
        JCountry jcountry = new JCountry();
        CountryDB countryDB = jcountry.getCountriesDB();
        assertNotNull(countryDB, "getCountriesDB should return an instance of the countries DB");

        ArrayList countries = countryDB.getCountries(Locale.GERMAN);
        assertNotNull(countries);
        assertTrue(!countries.isEmpty());
    }
}
